# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c72d846e477d670ddfc83df86dfdfea2742417117d299260a54675d04cf838ed9a22e871a17b88c02a6817a8df6812dd7fccf9c8104df4a77a32205961544a6

test:
  secret_key_base: 5bee348e69d26a5afc7d09343ba2ab1bf477993b618de0365460af8a2c25d3b0543740b89e7587f2bcbad6050b1be67de25363f1821c1111ab05ce9e415f97e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
